name: Testing configuration variable
on:
  workflow_dispatch
env:
    car: beat
jobs:
    car_name:
        runs-on: ubuntu-latest
        env:
            owner: barath
        steps:
            - name: "car ownership"
              run: echo "$owner owns a ${{vars.V_CAR_COLOR}} color  $car"
